version: "3.5"
services:
  postgres:
    build:
      context: ./postgres
    image: olx_postgres_image
    container_name: olx_postgres_container
    ports:
      - "7432:5432"
    env_file: ./postgres/.env